### ISSUE TITLE
ModuleNotFoundError: No module named 'mitosheet.pro.updates'

### ISSUE THREAD

**Issue by wuweihuazhangyixing** [mito-ds/monorepo#769]
I followed the instruction to install mito on Ancaonda Navigator, but it seemed something was wrong and I got the warning "ModuleNotFoundError: No module named 'mitosheet.pro.updates'".  I didn't know why. Somebody helps me ?
![image](https://github.com/mito-ds/monorepo/assets/108985937/a229f54c-0f79-422d-ac10-7e85be4c94f9)
![image](https://github.com/mito-ds/monorepo/assets/108985937/e5d78f1c-1265-4d90-afc4-52ee05c9bf47)

**Comment by aarondr77** [comment]
Hey @wuweihuazhangyixing sorry about that! Just got up a fix and it should be working now if you upgrade to the newest version of Mito -- thanks for reporting.

**Comment by wuweihuazhangyixing** [comment]
Thanks for your reply! I tried to upgrade mito but it was still the same warning.








sehun
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mito-ds/monorepo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 晚上9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mito-ds/monorepo] ModuleNotFoundError: No module named 'mitosheet.pro.updates' (Issue #769)





 
Hey @wuweihuazhangyixing sorry about that! Just got up a fix and it should be working now if you upgrade to the newest version of Mito -- thanks for reporting.

**Comment by wuweihuazhangyixing** [comment]
I have no idea. How could I check the version?


sehun
***@***.***


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mito-ds/monorepo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mito-ds/monorepo] ModuleNotFoundError: No module named 'mitosheet.pro.updates' (Issue #769)





 
Hey @wuweihuazhangyixing are you on the most recent release mitosheet 0.1.483?

**Comment by aarondr77** [comment]
In the first line of your Jupyter notebook, you can run the command `!pip list` and then check there version next to mitosheet.

**Comment by wuweihuazhangyixing** [comment]
Here are the versions.




sehun
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mito-ds/monorepo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mito-ds/monorepo] ModuleNotFoundError: No module named 'mitosheet.pro.updates' (Issue #769)





 
In the first line of your Jupyter notebook, you can run the command !pip list and then check there version next to mitosheet.

**Comment by aarondr77** [comment]
Got it. So try doing this:

1. close Jupyter (your browser tab and stop the server from running)
2. run the command `pip install mitosheet==0.1.483` in the same place that you installed Mito in the mito on Ancaonda Navigator before. 
3. Reopen Jupyter and try creating a mitosheet.

**Comment by wuweihuazhangyixing** [comment]
I made it! Thank you so much! Really really thankful and grateful! Hope you enjoy a happy life!




sehun
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mito-ds/monorepo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mito-ds/monorepo] ModuleNotFoundError: No module named 'mitosheet.pro.updates' (Issue #769)





 
Got it. So try doing this:
  
close Jupyter (your browser tab and stop the server from running)
 
run the command pip install mitosheet==0.1.483 in the same place that you installed Mito in the mito on Ancaonda Navigator before.
 
Reopen Jupyter and try creating a mitosheet.

**Comment by aarondr77** [comment]
Woohoo! Glad it worked out. Thanks again for sharing the feedback. If you have any more feedback as you use Mito, please let me know!
